#!/bin/sh
# -*- mode: shell-script; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
#
# Copyright (C) 2012, 2013 O.S. Systems Software LTDA.
# Authored-by:  Otavio Salvador <otavio@ossystems.com.br>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Adapted for the Genivi Demo platform by Johnny Karlsson, Volvo Cars 2015
#
SOURCES=`pwd`

if [ ! -f ".gdp" ]; then
    git submodule init
    git submodule update
    touch .gdp
fi

cd meta-genivi-demo/conf
TEMPLATECONF=`pwd`rget 
cd $SOURCES

cd poky/
. ./oe-init-build-env $SOURCES/build > /dev/null

cat << EOF
Welcome to the Genivi GDP build system

The build environment has been configured for the koelsh target.
Please follow the link below for instruction on how to obtain and install Renesas Graphics Drivers.

http://wiki.projects.genivi.org/index.php/Hardware_Setup_and_Software_Installation/koelsch%26porter

To start the build type:

bitbake genivi-demo-platform
EOF

