#!/bin/sh
# -*- mode: shell-script; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
#
# Copyright (C) 2012, 2013 O.S. Systems Software LTDA.
# Authored-by:  Otavio Salvador <otavio@ossystems.com.br>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Adapted for the Genivi Demo platform by Johnny Karlsson, Volvo Cars 2015
#
SOURCES=`pwd`
MACHINE=$1
if [ -z "$MACHINE" ]; then
    echo "Please select the development board you wish to target"
    echo "Currently supported boards are the Koelsh and the porter board"
    echo "Example: source ./setup-environment koelsh"
    return
fi
BUILD_FOLDER="gpd-build-$MACHINE"

git submodule init
git submodule update

cd meta-genivi-demo/conf
TEMPLATECONF=`pwd`rget 
cd $SOURCES

cd poky/
. ./oe-init-build-env $SOURCES/$BUILD_FOLDER > /dev/null

#Set up the bblayers and local conf
if [ ! -f ".gdp" ]; then
echo "hej"
cp $SOURCES/config/$MACHINE/* conf/
touch .gdp
fi

cat << EOF
Welcome to the Genivi GPD build system

The build environemnt has been configured for the $MACHINE target.
If you are targeting a Renesas board, please follow the link below for instruction on how
to obtain and install Renesas Graphics Drivers.

http://wiki.projects.genivi.org/index.php/Hardware_Setup_and_Software_Installation/koelsch%26porter

To start the build type:

bitbake genivi-demo-platform
EOF

